version: '3'

networks: 
  default: 
    external: 
      name: nginx-proxy_default

services:
  site:
    build:
      context: .
      dockerfile: dev_nginx.dockerfile
    container_name: nginx
    ports:
      - 8989:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
    networks: 
      default: 
        idv4_address: 172.21.0.99

  php:
    build:
      context: .
      dockerfile: dev_php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    networks: 
      default: 
        idv4_address: 172.21.0.100

  composer:
    build:
      context: .
      dockerfile: dev_composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  artisan:
    build:
      context: .
      dockerfile: dev_php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']