version: '3'

networks: 
  default: 
    external: 
      name: nginx-proxy_default

services:
  site:
    build:
      context: .
      dockerfile: nginx/dev/nginx.dockerfile
    container_name: nginx
    ports:
      - 8989:80
    volumes:
      - ./src:/var/www/html:default
    depends_on:
      - php

  php:
    build:
      context: .
      dockerfile: php/dev/php.dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:default

  composer:
    build:
      context: .
      dockerfile: composer/composer_dev.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']

  artisan:
    build:
      context: .
      dockerfile:  php/dev/php.dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html:default
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']