name: Laravel

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
          username: "api-sertifikasi"
          host: "api-sertifikasi.b4t.go.id"
          password: "api-sertifikasi"
          script: 'sh /home/api-sertifikasi/sertifikasi-be/deploy.sh'
