name: Laravel

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.USERNAME }}
          host: "52.187.66.134"
          port: "50171"
          password: ${{ secrets.PASSWORD }}
          script: "cd /home/b4t/PROD/sertifikasi-be && chmod +x /home/b4t/PROD/sertifikasi-be/deploy-prod.sh && sh /home/b4t/PROD/sertifikasi-be/deploy-prod.sh"
